name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        emacs_version:
          - 26.3
          - 27.2
          # - 28.0
          # - snapshot
    steps:
      - name: check out repo
        uses: actions/checkout@v1
      - name: Run tests
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        run: |
          emacs --version
          tests/test.sh
